version: '3'

services:
  db:
    image: mysql:latest #latest는 가장 최신버전
    ports: #사용할 포트
      - 3060:3060
    volumes: #경로설정
      - D:/mysql/data:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: mydb
    command:
       - --character-set-server=utf8mb4
 
  
    
