version: '3'

services:
  db:
    image: mysql:latest #latest는 가장 최신버전
    ports: #사용할 포트
      - 3307:3306
    restart: always
    volumes: #경로설정
      - D:/mysql/data:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: mydb
      MYSQL_ROOT_PASSWORD: 1234
    command:
       - --character-set-server=utf8mb4
 
  
    
